#!/usr/bin/perl

use strict;
use warnings;

my $outfile = "acceptance_tests";
open OUTPUT, ">$outfile" or die $!;
my $c = 97;
print OUTPUT "1 1\n";
print OUTPUT "1 2\n";
print OUTPUT "1 5\n";

my $a = 0;
my $b = 0;
sub gen_rand( $ ) {
   my $max = shift;
   $a = int(rand($max));
   $b = int(rand($max));
}

while ($c) {
   if( $c > 70) {
      gen_rand(500);
   }
   elsif( $c > 50) {
      gen_rand(5000);
   }
   elsif( $c > 25) {
      gen_rand(50000);
   }
   elsif( $c > 10) {
      gen_rand(500000)
   }
   elsif( $c > 5) {
      gen_rand(5000000)
   }
   else {
      gen_rand(50000000);
   }
   print OUTPUT "$a $b\n";
   $c--;
}
