#!/usr/bin/perl

use warnings;
use strict;

#my $prefix = "../collatz-tests/";
`mkdir mytests`
my $cmd = "ls -1 ../collatz-tests/*RunCollatz.in";
my @files = `$cmd`;

foreach my $file(@files){
   chomp $file;
   #print "file is \"$file\"\n";
   my $outfile = $file;
   $outfile =~ s/\.in/\.out/;
   $outfile =~ s/\.\.\/collatz-tests\///;

   $cmd = "./RunCollatz.py <$file >$outfile";
   print "cmd: \"$cmd\"\n";
   #`$cmd`;
}

